import type { EnemyDef, EnemyId, TowerDef, TowerId } from "./types";

export const CELL = 1.7;
export const STEP = 1 / 60;
export const MAX_ENEMIES = 96;
export const MAX_BOLTS = 80;
export const MAX_BEAMS = 48;
export const MAX_BURSTS = 48;
export const MAX_FLOATERS = 24;
export const MAX_DECALS = 20;
export const SURGE_CD = 22;
export const OVERCLOCK_CD = 20;
export const OVERCLOCK_DUR = 6.5;
export const SYN_RANGE = 3.45;
export const AUTO_WAVE_DELAY = 2.8;
export const SALVAGE_RATE = 0.6;
export const SPEED_STEPS = [1, 2, 3] as const;

export const TOWERS: Record<TowerId, TowerDef> = {
  pulse: {
    id: "pulse",
    name: "Pulse Battery",
    short: "Pulse",
    cost: 80,
    range: 5.4,
    fireRate: 1.2,
    damage: 18,
    kind: "bolt",
    hitsFlying: false,
    splash: 0,
    slow: 0,
    slowTime: 0,
    chain: 0,
    pierce: false,
    color: "#9db4c4",
    desc: "Stabilized plasma bolts. Ground only. Reliable backbone.",
  },
  arc: {
    id: "arc",
    name: "Arc Lance",
    short: "Lance",
    cost: 110,
    range: 6.6,
    fireRate: 2.5,
    damage: 9,
    kind: "beam",
    hitsFlying: true,
    splash: 0,
    slow: 0,
    slowTime: 0,
    chain: 0,
    pierce: false,
    color: "#7ec8c8",
    desc: "Photon lance. Hits air. Fast, precise, light per shot.",
  },
  frost: {
    id: "frost",
    name: "Frost Mortar",
    short: "Frost",
    cost: 140,
    range: 5.9,
    fireRate: 0.55,
    damage: 24,
    kind: "shell",
    hitsFlying: false,
    splash: 2.15,
    slow: 0.48,
    slowTime: 2.4,
    chain: 0,
    pierce: false,
    color: "#8ab4d4",
    desc: "Cryogenic splash. Slows packs. Ground only.",
  },
  rail: {
    id: "rail",
    name: "Rail Piercer",
    short: "Rail",
    cost: 185,
    range: 8.6,
    fireRate: 0.36,
    damage: 78,
    kind: "rail",
    hitsFlying: true,
    splash: 0,
    slow: 0,
    slowTime: 0,
    chain: 0,
    pierce: true,
    color: "#c4c0b4",
    desc: "Linear gauss. Pierces a line. Tears armor and air.",
  },
  tesla: {
    id: "tesla",
    name: "Tesla Spire",
    short: "Tesla",
    cost: 160,
    range: 4.9,
    fireRate: 0.92,
    damage: 17,
    kind: "chain",
    hitsFlying: true,
    splash: 0,
    slow: 0,
    slowTime: 0,
    chain: 3,
    pierce: false,
    color: "#8eb8a8",
    desc: "Arcing current. Jumps between nearby targets.",
  },
};

export const TOWER_ORDER: TowerId[] = ["pulse", "arc", "frost", "tesla", "rail"];

/** Copy for the inspector: what the next rank buys, and the name of the rank 3 overdrive. */
export const RANK_NOTES: Record<TowerId, { r2: string; overdrive: string; r3: string }> = {
  pulse: {
    r2: "Heavier bolts, faster cycle, wider reach.",
    overdrive: "Twin Pulse",
    r3: "Fires two bolts every cycle.",
  },
  arc: {
    r2: "Hotter lance, faster tick, longer reach.",
    overdrive: "Wide Lance",
    r3: "Beam thickens and splits to a second host.",
  },
  frost: {
    r2: "Colder shell, wider burst, longer reach.",
    overdrive: "Deep Freeze",
    r3: "Bigger splash, deeper slow, longer hold.",
  },
  tesla: {
    r2: "Stronger current and one more jump.",
    overdrive: "Cascade",
    r3: "One extra jump on top of the rank gain.",
  },
  rail: {
    r2: "Denser slug, faster charge, longer line.",
    overdrive: "Heavy Line",
    r3: "Pierce corridor widens to catch packs.",
  },
};

export const ENEMIES: Record<EnemyId, EnemyDef> = {
  mite: {
    id: "mite",
    name: "Mite",
    faction: "organic",
    hp: 30,
    speed: 2.45,
    gold: 6,
    armor: 0,
    flying: false,
    scale: 0.72,
    leak: 1,
  },
  brood: {
    id: "brood",
    name: "Broodling",
    faction: "organic",
    hp: 74,
    speed: 1.72,
    gold: 12,
    armor: 1,
    flying: false,
    scale: 1,
    leak: 1,
  },
  husk: {
    id: "husk",
    name: "Husk",
    faction: "organic",
    hp: 190,
    speed: 1.12,
    gold: 22,
    armor: 4,
    flying: false,
    scale: 1.38,
    leak: 2,
  },
  spore: {
    id: "spore",
    name: "Spore",
    faction: "organic",
    hp: 38,
    speed: 2.15,
    gold: 10,
    armor: 0,
    flying: true,
    scale: 0.82,
    leak: 1,
  },
  titan: {
    id: "titan",
    name: "Titan",
    faction: "organic",
    hp: 1450,
    speed: 0.84,
    gold: 90,
    armor: 8,
    flying: false,
    scale: 2.2,
    leak: 5,
    boss: true,
  },
  myrmidon: {
    id: "myrmidon",
    name: "Myrmidon",
    faction: "organic",
    hp: 380,
    speed: 1.05,
    gold: 36,
    armor: 6,
    flying: false,
    scale: 1.58,
    leak: 3,
  },
  bloom: {
    id: "bloom",
    name: "Bloom",
    faction: "organic",
    hp: 95,
    speed: 2.32,
    gold: 18,
    armor: 1,
    flying: true,
    scale: 0.98,
    leak: 1,
  },
  colossus: {
    id: "colossus",
    name: "Colossus",
    faction: "organic",
    hp: 3200,
    speed: 0.68,
    gold: 160,
    armor: 12,
    flying: false,
    scale: 2.7,
    leak: 8,
    boss: true,
  },
  drone: {
    id: "drone",
    name: "Drone",
    faction: "mech",
    hp: 34,
    speed: 2.55,
    gold: 7,
    armor: 1,
    flying: false,
    scale: 0.76,
    leak: 1,
  },
  walker: {
    id: "walker",
    name: "Walker",
    faction: "mech",
    hp: 96,
    speed: 1.48,
    gold: 14,
    armor: 5,
    flying: false,
    scale: 1.12,
    leak: 1,
  },
  siege: {
    id: "siege",
    name: "Siege Unit",
    faction: "mech",
    hp: 230,
    speed: 1.02,
    gold: 26,
    armor: 8,
    flying: false,
    scale: 1.42,
    leak: 2,
  },
  gunship: {
    id: "gunship",
    name: "Gunship",
    faction: "mech",
    hp: 52,
    speed: 2.2,
    gold: 12,
    armor: 2,
    flying: true,
    scale: 0.92,
    leak: 1,
  },
  dread: {
    id: "dread",
    name: "Dreadnought",
    faction: "mech",
    hp: 1680,
    speed: 0.8,
    gold: 100,
    armor: 12,
    flying: false,
    scale: 2.28,
    leak: 5,
    boss: true,
  },
  bulwark: {
    id: "bulwark",
    name: "Bulwark",
    faction: "mech",
    hp: 420,
    speed: 0.95,
    gold: 40,
    armor: 11,
    flying: false,
    scale: 1.58,
    leak: 3,
  },
  razor: {
    id: "razor",
    name: "Razor",
    faction: "mech",
    hp: 110,
    speed: 2.38,
    gold: 20,
    armor: 3,
    flying: true,
    scale: 1.02,
    leak: 1,
  },
  leviathan: {
    id: "leviathan",
    name: "Leviathan",
    faction: "mech",
    hp: 3600,
    speed: 0.64,
    gold: 180,
    armor: 16,
    flying: false,
    scale: 2.75,
    leak: 8,
    boss: true,
  },
  chimera: {
    id: "chimera",
    name: "Chimera",
    faction: "hybrid",
    hp: 118,
    speed: 1.78,
    gold: 16,
    armor: 3,
    flying: false,
    scale: 1.16,
    leak: 1,
  },
  wraith: {
    id: "wraith",
    name: "Wraith",
    faction: "hybrid",
    hp: 58,
    speed: 2.35,
    gold: 14,
    armor: 1,
    flying: true,
    scale: 0.88,
    leak: 1,
  },
  overlord: {
    id: "overlord",
    name: "Overlord",
    faction: "hybrid",
    hp: 2100,
    speed: 0.76,
    gold: 130,
    armor: 10,
    flying: false,
    scale: 2.45,
    leak: 6,
    boss: true,
  },
  amalgam: {
    id: "amalgam",
    name: "Amalgam",
    faction: "hybrid",
    hp: 280,
    speed: 1.42,
    gold: 32,
    armor: 5,
    flying: false,
    scale: 1.42,
    leak: 2,
  },
  specter: {
    id: "specter",
    name: "Specter",
    faction: "hybrid",
    hp: 120,
    speed: 2.52,
    gold: 22,
    armor: 2,
    flying: true,
    scale: 1.02,
    leak: 1,
  },
  sovereign: {
    id: "sovereign",
    name: "Sovereign",
    faction: "hybrid",
    hp: 4200,
    speed: 0.62,
    gold: 200,
    armor: 14,
    flying: false,
    scale: 2.9,
    leak: 9,
    boss: true,
  },
};

export function upgradeCost(base: number, level: number) {
  return Math.round(base * 0.72 * level);
}

export function towerStats(def: TowerDef, level: number) {
  const l = level - 1;
  return {
    range: def.range * (1 + l * 0.12),
    fireRate: def.fireRate * (1 + l * 0.14),
    damage: def.damage * (1 + l * 0.55),
    splash: def.splash * (1 + l * 0.12),
    chain: def.chain + (l > 0 ? l : 0),
  };
}

/**
 * Worlds separate on value first, hue second: near-black ground, a mid-value
 * arena floor, and the path carrying the only saturated light on the field.
 */
export const PLANET_THEME = {
  mycelion: {
    sky: "#050d0b",
    fog: "#081411",
    hemiSky: "#5d8a7c",
    hemiGround: "#050c09",
    dir: "#d4f0e2",
    ground: "#080f0c",
    groundHi: "#122a20",
    path: "#17392c",
    pathEmissive: "#35c894",
    pad: "#33473f",
    padEmi: "#3dcaa0",
    core: "#3dcaa0",
    ambient: "#0f2820",
  },
  forge: {
    sky: "#0a0706",
    fog: "#130d0a",
    hemiSky: "#a07868",
    hemiGround: "#0f0705",
    dir: "#ffd0a4",
    ground: "#0f0c0a",
    groundHi: "#241c17",
    path: "#33291f",
    pathEmissive: "#e2661c",
    pad: "#4c3f36",
    padEmi: "#e08848",
    core: "#f09a52",
    ambient: "#20120a",
  },
  aegis: {
    sky: "#06090e",
    fog: "#0a1016",
    hemiSky: "#8098ac",
    hemiGround: "#080c10",
    dir: "#e4eef8",
    ground: "#0a0e13",
    groundHi: "#18222b",
    path: "#25333c",
    pathEmissive: "#6cc4d0",
    pad: "#3a4650",
    padEmi: "#9fd8de",
    core: "#a8dce4",
    ambient: "#121a22",
  },
} as const;
